import sys
start_frame=int(sys.argv[1])
num_frames=int(sys.argv[2])
IMAGE_DIR = "/grand/projects/alcf_training/visualization/FRAMES/2026/BLOOD_01"


# state file generated using paraview version 6.0.0
import paraview
paraview.compatibility.major = 6
paraview.compatibility.minor = 0

#### import the simple module from the paraview
from paraview.simple import *
#### disable automatic camera reset on 'Show'
paraview.simple._DisableFirstRenderCameraReset()

# ----------------------------------------------------------------
# setup views used in the visualization
# ----------------------------------------------------------------

# get the material library
materialLibrary1 = GetMaterialLibrary()

# Create a new 'Render View'
renderView1 = CreateView('RenderView')
renderView1.Set(
    UseCache=0,
    ViewSize=[1078, 772],
    UseInteractiveRenderingForScreenshots=0,
    InteractionMode='3D',
    CollectGeometryThreshold=100.0,
    SuppressRendering=0,
    AxesGrid='Grid Axes 3D Actor',
    Visible=0,
    Size=100,
    Location='Top Right',
    CenterAxesVisibility=0,
    OrientationAxesVisibility=0,
    OrientationAxesInteractivity=0,
    OrientationAxesXVisibility=1,
    OrientationAxesYVisibility=1,
    OrientationAxesZVisibility=1,
    OrientationAxesXColor=[1.0, 0.0, 0.0],
    OrientationAxesYColor=[1.0, 1.0, 0.0],
    OrientationAxesZColor=[0.0, 1.0, 0.0],
    OrientationAxesXLabelText='X',
    OrientationAxesYLabelText='Y',
    OrientationAxesZLabelText='Z',
    CenterOfRotation=[19.999000549316406, 0.0014500617980957031, 0.0034999847412109375],
    RotationFactor=1.0,
    EnableRenderOnInteraction=1,
    UseLight=1,
    KeyLightWarmth=0.6,
    KeyLightIntensity=0.75,
    KeyLightElevation=50.0,
    KeyLightAzimuth=10.0,
    FillLightWarmth=0.4,
    FillLightKFRatio=3.0,
    FillLightElevation=-75.0,
    FillLightAzimuth=-10.0,
    BackLightWarmth=0.5,
    BackLightKBRatio=3.5,
    BackLightElevation=0.0,
    BackLightAzimuth=110.0,
    HeadLightWarmth=0.5,
    HeadLightKHRatio=3.0,
    MaintainLuminance=0,
    HiddenLineRemoval=0,
    UseToneMapping=0,
    Exposure=1.0,
    UseAmbientOcclusion=0,
    StereoRender=0,
    StereoType='Crystal Eyes',
    ServerStereoType='Same As Client',
    MultiSamples=0,
    AlphaBitPlanes=1,
    StencilCapable=1,
    CameraPosition=[26.87397423530047, -4.199407731197718, 73.2628362246417],
    CameraFocalPoint=[17.93273829340339, 1.2640110978965253, -22.014475396655953],
    CameraViewUp=[0.22480519080059602, 0.9737841637941916, 0.03474231616854028],
    CameraViewAngle=30.0,
    CameraFocalDisk=1.0,
    CameraFocalDistance=0.0,
    CameraParallelScale=24.808262155891853,
    EyeAngle=2.0,
    PhysicalToWorldMatrix=[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    EnableSynchronizableActors=0,
    CameraParallelProjection=0,
    LegendGrid='Legend Grid Actor',
    PolarGrid='Polar Grid Actor',
    UseColorPaletteForBackground=1,
    BackgroundColorMode='Single Color',
    BackgroundTexture=None,
    Background2=[0.0, 0.0, 0.165],
    Background=[0.32, 0.34, 0.43],
    UseEnvironmentLighting=0,
    MaxClipBounds=[0.0, -1.0, 0.0, -1.0, 0.0, -1.0],
    LockBounds=0,
    EnableRayTracing=0,
    BackEnd='OSPRay raycaster',
    Shadows=0,
    AmbientSamples=0,
    SamplesPerPixel=1,
    ProgressivePasses=1,
    RouletteDepth=5,
    VolumeAnisotropy=0.0,
    Denoise=1,
    LightScale=1.0,
    TemporalCacheSize=0,
    Backgroundmode='Environment',
    EnvironmentNorth=[0.0, 1.0, 0.0],
    EnvironmentEast=[1.0, 0.0, 0.0],
    EnvironmentalBG=[0.384313725, 0.364705882, 0.352941176],
    EnvironmentalBG2=[0.0, 0.0, 0.165],
    UseGradientEnvironmentalBG=0,
    UseTexturedEnvironmentalBG=0,
    EnvironmentalBGTexture=None,
    AdditionalLights=[],
    OSPRayMaterialLibrary=materialLibrary1,
    SetHardwareSelector=None,
)

# init the 'Grid Axes 3D Actor' selected for 'AxesGrid'
renderView1.AxesGrid.Set(
    Visibility=0,
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleOpacity=1.0,
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleShadow=0,
    XTitleFontSize=12,
    YTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleShadow=0,
    YTitleFontSize=12,
    ZTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleShadow=0,
    ZTitleFontSize=12,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    AxesToLabel=63,
    LabelUniqueEdgesOnly=1,
    XLabelOpacity=1.0,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelShadow=0,
    XLabelFontSize=12,
    YLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelShadow=0,
    YLabelFontSize=12,
    ZLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelShadow=0,
    ZLabelFontSize=12,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    DataScale=[1.0, 1.0, 1.0],
    DataPosition=[0.0, 0.0, 0.0],
    DataBoundsScaleFactor=1.0008,
    ModelTransformMatrix=[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    ModelBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    UseModelTransform=0,
)

# init the 'Legend Grid Actor' selected for 'LegendGrid'
renderView1.LegendGrid.Set(
    Visibility=0,
    GridColor=[1.0, 1.0, 1.0],
    GridVisibility=0,
    RightBorderOffset=50,
    TopBorderOffset=30,
    LeftBorderOffset=50,
    BottomBorderOffset=30,
    LegendLabelOpacity=1.0,
    LegendLabelFontFamily='Arial',
    LegendLabelFontFile='',
    LegendLabelBold=0,
    LegendLabelItalic=0,
    LegendLabelShadow=0,
    LegendLabelFontSize=12,
    AxisNotation='Default',
    AxisPrecision=2,
    HorizontalLabelNumber=5,
    VerticalLabelNumber=5,
    Origin=[0.0, 0.0, 0.0],
)

# init the 'Polar Grid Actor' selected for 'PolarGrid'
renderView1.PolarGrid.Set(
    Visibility=0,
    Origin=[0.5, 0.5],
    StartAngle=0.0,
    EndAngle=180.0,
    AxesLength=100.0,
    NumberOfAxes=6,
    NumberOfTicks=6,
    GridColor=[1.0, 1.0, 1.0],
    AxesLabelFontFamily='Arial',
    AxesLabelBold=0,
    AxesLabelItalic=0,
    AxesLabelShadow=0,
    AxesLabelFontSize=12,
)

SetActiveView(None)

# ----------------------------------------------------------------
# setup view layouts
# ----------------------------------------------------------------

# create new layout object 'Layout #1'
layout1 = CreateLayout(name='Layout #1')
layout1.AssignView(0, renderView1)
layout1.SetSize(1078, 772)

# ----------------------------------------------------------------
# restore active view
SetActiveView(renderView1)
# ----------------------------------------------------------------

# ----------------------------------------------------------------
# setup the data processing pipelines
# ----------------------------------------------------------------

# create a new 'XML PolyData Reader'
rbc_bad_step_0000vtp = XMLPolyDataReader(registrationName='rbc_bad_step_0000.vtp*', FileName=['/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0000.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0001.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0002.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0003.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0004.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0005.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0006.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0007.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0008.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0009.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0010.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0011.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0012.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0013.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0014.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0015.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0016.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0017.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0018.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0019.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0020.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0021.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0022.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0023.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0024.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0025.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0026.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0027.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0028.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0029.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0030.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0031.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0032.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0033.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0034.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0035.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0036.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0037.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0038.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0039.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0040.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0041.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0042.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0043.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0044.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0045.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0046.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0047.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0048.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0049.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0050.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0051.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0052.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0053.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0054.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0055.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0056.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0057.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0058.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0059.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0060.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0061.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0062.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0063.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0064.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0065.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0066.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0067.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0068.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0069.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0070.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0071.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0072.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0073.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0074.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0075.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0076.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0077.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0078.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0079.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0080.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0081.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0082.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0083.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0084.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0085.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0086.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0087.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0088.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0089.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0090.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0091.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0092.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0093.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0094.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0095.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0096.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0097.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0098.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_bad_step_0099.vtp'])
rbc_bad_step_0000vtp.Set(
    CellArrayStatus=[],
    PointArrayStatus=['Velocity', 'Normals'],
    TimeArray='None',
)

# create a new 'XML PolyData Reader'
rbc_good_step_0000vtp = XMLPolyDataReader(registrationName='rbc_good_step_0000.vtp*', FileName=['/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0000.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0001.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0002.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0003.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0004.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0005.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0006.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0007.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0008.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0009.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0010.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0011.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0012.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0013.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0014.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0015.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0016.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0017.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0018.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0019.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0020.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0021.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0022.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0023.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0024.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0025.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0026.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0027.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0028.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0029.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0030.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0031.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0032.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0033.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0034.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0035.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0036.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0037.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0038.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0039.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0040.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0041.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0042.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0043.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0044.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0045.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0046.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0047.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0048.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0049.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0050.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0051.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0052.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0053.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0054.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0055.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0056.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0057.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0058.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0059.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0060.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0061.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0062.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0063.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0064.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0065.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0066.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0067.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0068.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0069.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0070.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0071.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0072.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0073.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0074.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0075.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0076.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0077.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0078.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0079.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0080.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0081.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0082.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0083.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0084.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0085.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0086.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0087.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0088.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0089.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0090.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0091.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0092.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0093.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0094.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0095.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0096.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0097.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0098.vtp', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/rbc_good_step_0099.vtp'])
rbc_good_step_0000vtp.Set(
    CellArrayStatus=[],
    PointArrayStatus=['Velocity', 'Normals'],
    TimeArray='None',
)

# create a new 'XML Unstructured Grid Reader'
artery_step_0000vtu = XMLUnstructuredGridReader(registrationName='artery_step_0000.vtu*', FileName=['/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0000.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0001.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0002.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0003.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0004.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0005.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0006.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0007.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0008.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0009.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0010.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0011.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0012.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0013.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0014.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0015.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0016.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0017.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0018.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0019.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0020.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0021.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0022.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0023.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0024.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0025.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0026.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0027.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0028.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0029.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0030.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0031.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0032.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0033.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0034.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0035.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0036.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0037.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0038.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0039.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0040.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0041.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0042.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0043.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0044.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0045.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0046.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0047.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0048.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0049.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0050.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0051.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0052.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0053.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0054.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0055.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0056.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0057.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0058.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0059.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0060.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0061.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0062.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0063.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0064.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0065.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0066.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0067.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0068.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0069.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0070.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0071.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0072.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0073.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0074.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0075.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0076.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0077.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0078.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0079.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0080.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0081.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0082.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0083.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0084.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0085.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0086.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0087.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0088.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0089.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0090.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0091.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0092.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0093.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0094.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0095.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0096.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0097.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0098.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/artery_step_0099.vtu'])
artery_step_0000vtu.Set(
    CellArrayStatus=[],
    PointArrayStatus=['Count', 'Velocity'],
    TimeArray='None',
)

# create a new 'XML Unstructured Grid Reader'
particles_step_0000vtu = XMLUnstructuredGridReader(registrationName='particles_step_0000.vtu*', FileName=['/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0000.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0001.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0002.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0003.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0004.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0005.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0006.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0007.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0008.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0009.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0010.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0011.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0012.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0013.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0014.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0015.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0016.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0017.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0018.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0019.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0020.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0021.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0022.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0023.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0024.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0025.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0026.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0027.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0028.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0029.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0030.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0031.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0032.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0033.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0034.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0035.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0036.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0037.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0038.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0039.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0040.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0041.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0042.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0043.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0044.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0045.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0046.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0047.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0048.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0049.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0050.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0051.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0052.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0053.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0054.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0055.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0056.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0057.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0058.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0059.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0060.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0061.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0062.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0063.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0064.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0065.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0066.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0067.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0068.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0069.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0070.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0071.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0072.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0073.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0074.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0075.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0076.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0077.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0078.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0079.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0080.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0081.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0082.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0083.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0084.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0085.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0086.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0087.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0088.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0089.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0090.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0091.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0092.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0093.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0094.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0095.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0096.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0097.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0098.vtu', '/grand/projects/alcf_training/visualization/BLOODFLOW_TUTORIAL_DATA/particles_step_0099.vtu'])
particles_step_0000vtu.Set(
    CellArrayStatus=[],
    PointArrayStatus=['X Velocity Direction', 'Velocity'],
    TimeArray='None',
)

# create a new 'Glyph'
glyph1 = Glyph(registrationName='Glyph1', Input=particles_step_0000vtu,
    GlyphType='Sphere')
glyph1.Set(
    OrientationArray=['POINTS', 'Velocity'],
    ScaleArray=['POINTS', 'No scale array'],
    VectorScaleMode='Scale by Magnitude',
    ScaleFactor=1.0,
    GlyphTransform='Transform2',
    GlyphMode='Every Nth Point',
    MaximumNumberOfSamplePoints=5000,
    Seed=10339,
    Stride=10,
)

# init the 'Sphere' selected for 'GlyphType'
glyph1.GlyphType.Set(
    Center=[0.0, 0.0, 0.0],
    Radius=0.2,
    ThetaResolution=16,
    StartTheta=0.0,
    EndTheta=360.0,
    PhiResolution=16,
    StartPhi=0.0,
    EndPhi=180.0,
)

# init the 'Transform2' selected for 'GlyphTransform'
glyph1.GlyphTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# ----------------------------------------------------------------
# setup the visualization in view 'renderView1'
# ----------------------------------------------------------------

# show data from rbc_bad_step_0000vtp
rbc_bad_step_0000vtpDisplay = Show(rbc_bad_step_0000vtp, renderView1, 'GeometryRepresentation')

# trace defaults for the display properties.
rbc_bad_step_0000vtpDisplay.Set(
    Selection=None,
    Representation='Surface',
    AmbientColor=[0.0, 1.0, 1.0],
    ColorArrayName=[None, ''],
    DiffuseColor=[0.0, 1.0, 1.0],
    LookupTable=None,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=1.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='Normals',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='Normals',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='Velocity',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=4.5540001630783085,
    SelectScaleArray='None',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='None',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.22770000815391542,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=['POINTS', 'Normals'],
    ScaleArrayComponent='X',
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=['POINTS', 'Normals'],
    OpacityArrayComponent='X',
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    SelectInputVectors=['POINTS', 'Velocity'],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
rbc_bad_step_0000vtpDisplay.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
rbc_bad_step_0000vtpDisplay.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
rbc_bad_step_0000vtpDisplay.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
rbc_bad_step_0000vtpDisplay.ScaleTransferFunction.Set(
    Points=[-0.9994208812713623, 0.0, 0.5, 0.0, 0.9991291165351868, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
rbc_bad_step_0000vtpDisplay.OpacityTransferFunction.Set(
    Points=[-0.9994208812713623, 0.0, 0.5, 0.0, 0.9991291165351868, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
rbc_bad_step_0000vtpDisplay.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
rbc_bad_step_0000vtpDisplay.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# show data from artery_step_0000vtu
artery_step_0000vtuDisplay = Show(artery_step_0000vtu, renderView1, 'UnstructuredGridRepresentation')

# trace defaults for the display properties.
artery_step_0000vtuDisplay.Set(
    Selection=None,
    Representation='Surface',
    ColorArrayName=['POINTS', ''],
    LookupTable=None,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=0.25,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='None',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='Count',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='Velocity',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=3.8554580688476565,
    SelectScaleArray='Count',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='Count',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.19277290344238282,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=['POINTS', 'Count'],
    ScaleArrayComponent='',
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=['POINTS', 'Count'],
    OpacityArrayComponent='',
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    ScalarOpacityFunction=None,
    ScalarOpacityUnitDistance=1.1270005945652875,
    UseSeparateOpacityArray=0,
    OpacityArrayName=['POINTS', 'Count'],
    OpacityComponent='',
    SelectMapper='Projected tetra',
    SamplingDimensions=[128, 128, 128],
    UseFloatingPointFrameBuffer=1,
    SelectInputVectors=['POINTS', 'Velocity'],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
artery_step_0000vtuDisplay.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
artery_step_0000vtuDisplay.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
artery_step_0000vtuDisplay.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
artery_step_0000vtuDisplay.ScaleTransferFunction.Set(
    Points=[355.0, 0.0, 0.5, 0.0, 6422.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
artery_step_0000vtuDisplay.OpacityTransferFunction.Set(
    Points=[355.0, 0.0, 0.5, 0.0, 6422.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
artery_step_0000vtuDisplay.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
artery_step_0000vtuDisplay.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# show data from rbc_good_step_0000vtp
rbc_good_step_0000vtpDisplay = Show(rbc_good_step_0000vtp, renderView1, 'GeometryRepresentation')

# trace defaults for the display properties.
rbc_good_step_0000vtpDisplay.Set(
    Selection=None,
    Representation='Surface',
    AmbientColor=[0.8509804010391235, 0.0, 0.0],
    ColorArrayName=[None, ''],
    DiffuseColor=[0.8509804010391235, 0.0, 0.0],
    LookupTable=None,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.75,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='Normals',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='Normals',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='Velocity',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=4.37199981212616,
    SelectScaleArray='None',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='None',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.218599990606308,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=['POINTS', 'Normals'],
    ScaleArrayComponent='X',
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=['POINTS', 'Normals'],
    OpacityArrayComponent='X',
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    SelectInputVectors=['POINTS', 'Velocity'],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
rbc_good_step_0000vtpDisplay.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
rbc_good_step_0000vtpDisplay.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
rbc_good_step_0000vtpDisplay.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
rbc_good_step_0000vtpDisplay.ScaleTransferFunction.Set(
    Points=[-0.9997668266296387, 0.0, 0.5, 0.0, 0.9994969964027405, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
rbc_good_step_0000vtpDisplay.OpacityTransferFunction.Set(
    Points=[-0.9997668266296387, 0.0, 0.5, 0.0, 0.9994969964027405, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
rbc_good_step_0000vtpDisplay.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
rbc_good_step_0000vtpDisplay.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# show data from glyph1
glyph1Display = Show(glyph1, renderView1, 'GeometryRepresentation')

# get 2D transfer function for 'Velocity'
velocityTF2D = GetTransferFunction2D('Velocity')
velocityTF2D.Set(
    AutomaticRescaleRangeMode="Grow and update on 'Apply'",
    Boxes=[],
    ScalarRangeInitialized=0,
    Range=[0.0, 1.0, 0.0, 1.0],
    OutputDimensions=[10, 10],
)

# get color transfer function/color map for 'Velocity'
velocityLUT = GetColorTransferFunction('Velocity')
velocityLUT.Set(
    InterpretValuesAsCategories=0,
    AnnotationsInitialized=0,
    ShowCategoricalColorsinDataRangeOnly=0,
    AutomaticRescaleRangeMode="Grow and update on 'Apply'",
    RescaleOnVisibilityChange=0,
    TransferFunction2D=velocityTF2D,
    RGBPoints=GenerateRGBPoints(
        range_min=0.0,
        range_max=0.5584595933111053,
    ),
    UseLogScale=0,
    UseOpacityControlPointsFreehandDrawing=0,
    ShowDataHistogram=0,
    AutomaticDataHistogramComputation=0,
    DataHistogramNumberOfBins=10,
    ColorSpace='Lab',
    UseBelowRangeColor=0,
    BelowRangeColor=[0.0, 0.0, 0.0],
    UseAboveRangeColor=0,
    AboveRangeColor=[0.5, 0.5, 0.5],
    NanColor=[0.0, 1.0, 0.0],
    NanOpacity=1.0,
    Discretize=1,
    NumberOfTableValues=256,
    ScalarRangeInitialized=1.0,
    HSVWrap=0,
    VectorComponent=0,
    VectorMode='Magnitude',
    AllowDuplicateScalars=1,
    Annotations=[],
    ActiveAnnotatedValues=[],
    IndexedColors=[],
    IndexedOpacities=[],
    EnableOpacityMapping=0,
)

# trace defaults for the display properties.
glyph1Display.Set(
    Selection=None,
    Representation='Surface',
    ColorArrayName=['POINTS', 'Velocity'],
    LookupTable=velocityLUT,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='Normals',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='Normals',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='Velocity',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=4.396576523780823,
    SelectScaleArray='None',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='None',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.21982882618904115,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=['POINTS', 'Normals'],
    ScaleArrayComponent='X',
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=['POINTS', 'Normals'],
    OpacityArrayComponent='X',
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    SelectInputVectors=['POINTS', 'Velocity'],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
glyph1Display.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
glyph1Display.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
glyph1Display.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
glyph1Display.ScaleTransferFunction.Set(
    Points=[-0.9999991655349731, 0.0, 0.5, 0.0, 0.9999991655349731, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
glyph1Display.OpacityTransferFunction.Set(
    Points=[-0.9999991655349731, 0.0, 0.5, 0.0, 0.9999991655349731, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
glyph1Display.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
glyph1Display.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# ----------------------------------------------------------------
# setup color maps and opacity maps used in the visualization
# note: the Get..() functions create a new object, if needed
# ----------------------------------------------------------------

# get opacity transfer function/opacity map for 'Velocity'
velocityPWF = GetOpacityTransferFunction('Velocity')
velocityPWF.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 0.5584595933111053, 1.0, 0.5, 0.0],
    AllowDuplicateScalars=1,
    UseLogScale=0,
    ScalarRangeInitialized=1,
)

# ----------------------------------------------------------------
# setup animation scene, tracks and keyframes
# note: the Get..() functions create a new object, if needed
# ----------------------------------------------------------------

# get time animation track
timeAnimationCue1 = GetTimeTrack()

# initialize the animation scene
timeAnimationCue1.Set(
    TimeMode='Normalized',
    StartTime=0.0,
    EndTime=1.0,
    Enabled=1,
    KeyFrames=[],
    UseAnimationTime=1,
)

# get the time-keeper
timeKeeper1 = GetTimeKeeper()

# initialize the timekeeper
timeKeeper1.SuppressedTimeSources = []

# initialize the animation track
timeAnimationCue1.Set(
    TimeMode='Normalized',
    StartTime=0.0,
    EndTime=1.0,
    Enabled=1,
    KeyFrames=[],
    UseAnimationTime=1,
)

# get animation scene
animationScene1 = GetAnimationScene()

# initialize the animation scene
animationScene1.Set(
    ViewModules=renderView1,
    Cues=timeAnimationCue1,
    AnimationTime=0.0,
    StartTime=0.0,
    EndTime=99.0,
    LockStartTime=0,
    LockEndTime=0,
    ForceDisableCaching=0,
    Loop=0,
    PlayMode='Snap To TimeSteps',
    NumberOfFrames=1,
    FramesPerTimestep=1,
    Stride=1,
)

# ----------------------------------------------------------------
# restore active source
SetActiveSource(artery_step_0000vtu)
# ----------------------------------------------------------------


##--------------------------------------------
## You may need to add some code at the end of this python script depending on your usage, eg:
#
## Render all views to see them appears
# RenderAllViews()
#
## Interact with the view, usefull when running from pvpython
# Interact()
#
## Save a screenshot of the active view
# SaveScreenshot("path/to/screenshot.png")
#
## Save a screenshot of a layout (multiple splitted view)
# SaveScreenshot("path/to/screenshot.png", GetLayout())
#
## Save all "Extractors" from the pipeline browser
# SaveExtracts()
#
## Save a animation of the current active view
# SaveAnimation()
#
## Please refer to the documentation of paraview.simple
## https://www.paraview.org/paraview-docs/latest/python/paraview.simple.html
##--------------------------------------------

XRES = 1920
YRES = 1080  # set desired resolution                                                                                                           

time_vals = artery_step_0000vtu.TimestepValues    # find data reader object                                                                     
for i in range(start_frame, start_frame+num_frames):
    renderView1.ViewTime = time_vals[i]
    IMAGE_FILE="%s/frame_%04d.png" % (IMAGE_DIR, i)
    print ("saving: " + IMAGE_FILE)
    SaveScreenshot(IMAGE_FILE, renderView1, ImageResolution=[XRES, YRES])

